from setuptools import setup

setup(name='changeit3d',
      version='0.1',
      description='ShapeTalk: A Language Dataset and Framework for 3D Shape Edits and Deformations',
      url='https://github.com/optas/changeit3d',      
      packages=['changeit3d'],
      install_requires=['torch',
                        'matplotlib',
                        'scikit-learn',
                        'dask[dataframe]',
                        'nltk',
                        'Pillow',
                        'tqdm',
                        'jupyter',
                        'numpy',
                        'scipy',
                        'plyfile',
                        'pandas<2.0.0',                        
                        'tabulate',
                        'termcolor',
                        'inflect',
                        'dill',
                        'h5py',
                        'seaborn',                
                        'symspellpy==6.5.2'],
      zip_safe=False)